/* Data access layer over window.FAMILY_DATA (generated by scripts/build.py). */
(function () {
  'use strict';
  const raw = window.FAMILY_DATA || {};
  raw.people = raw.people || [];
  raw.families = raw.families || [];
  raw.stories = raw.stories || [];
  raw.confidenceLevels = raw.confidenceLevels || {};

  const peopleById = {}, familiesById = {}, familiesAsSpouse = {}, familyAsChild = {};
  raw.people.forEach(p => { peopleById[p.id] = p; });
  raw.families.forEach(f => {
    familiesById[f.id] = f;
    f.children = f.children || [];
    [f.husband, f.wife].forEach(s => { if (s) (familiesAsSpouse[s] = familiesAsSpouse[s] || []).push(f); });
    f.children.forEach(c => { familyAsChild[c] = f; });
  });

  /* ---------- Dates ---------- */
  const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
  const MON3 = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];

  function parseDate(str) {
    if (!str) return null;
    let s = String(str).trim();
    const out = { text: s, year: null, month: null, day: null, qualifier: '' };
    let m;
    const q = s.match(/^(ABT|ABOUT|CA|CIRCA|EST|BEF|BEFORE|AFT|AFTER|BET|BETWEEN|FROM|TO)\.?\s+(.*)$/i);
    if (q) {
      const qk = q[1].toUpperCase();
      out.qualifier = /^(ABT|ABOUT|CA|CIRCA|EST)$/.test(qk) ? 'about' : /^(BEF|BEFORE)$/.test(qk) ? 'before' : /^(AFT|AFTER)$/.test(qk) ? 'after' : 'between';
      s = q[2].split(/\s+(AND|TO)\s+/i)[0];
    }
    if ((m = s.match(/^(\d{4})(?:-(\d{1,2}))?(?:-(\d{1,2}))?$/))) {
      out.year = +m[1]; if (m[2]) out.month = +m[2]; if (m[3]) out.day = +m[3];
    } else if ((m = s.match(/^(?:(\d{1,2})\s+)?([A-Za-z]{3})[A-Za-z]*\.?\s+(\d{4})$/))) {
      const mi = MON3.indexOf(m[2].toUpperCase());
      out.year = +m[3]; if (mi >= 0) out.month = mi + 1; if (m[1]) out.day = +m[1];
    } else if ((m = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/))) {
      out.year = +m[3]; out.month = +m[1]; out.day = +m[2];
    } else if ((m = s.match(/(\d{4})/))) {
      out.year = +m[1];
    }
    return out;
  }
  function formatDate(str, short) {
    const d = parseDate(str);
    if (!d) return '';
    if (d.year === null) return d.text;
    if (/^\d{4}\s*[-–]\s*\d{4}$/.test(d.text)) return d.text.replace(/\s*[-–]\s*/, '–');
    const mon = d.month ? (short ? MONTHS[d.month - 1].slice(0, 3) : MONTHS[d.month - 1]) : '';
    const core = d.day && d.month ? `${d.day} ${mon} ${d.year}` : d.month ? `${mon} ${d.year}` : String(d.year);
    if (d.qualifier === 'between') return d.text.replace(/^BET(WEEN)?\s+/i, 'between ').replace(/\s+AND\s+/i, ' and ');
    return d.qualifier ? `${d.qualifier} ${core}` : core;
  }
  const year = str => { const d = parseDate(str); return d ? d.year : null; };
  function sortKey(str) {
    const d = parseDate(str);
    if (!d || d.year === null) return Infinity;
    return d.year * 10000 + (d.month || 0) * 100 + (d.day || 0);
  }

  /* ---------- People ---------- */
  const get = id => peopleById[id] || null;
  const all = () => raw.people.slice();
  function fullName(p) {
    if (!p) return 'Unknown';
    let n = [p.prefix, p.given, p.surname].filter(Boolean).join(' ');
    if (p.suffix) n += ' ' + p.suffix;
    return n || 'Unknown';
  }
  function shortName(p) {
    if (!p) return 'Unknown';
    return [(p.given || '').split(/\s+/)[0], p.surname].filter(Boolean).join(' ') || 'Unknown';
  }
  function firstName(p) { return p ? ((p.given || '').split(/\s+/)[0] || p.surname || 'Unknown') : 'Unknown'; }
  function initials(p) {
    if (!p) return '?';
    return ((p.given || '?')[0] + ((p.surname || '')[0] || '')).toUpperCase();
  }
  const birthYear = p => p && p.birth ? year(p.birth.date) : null;
  const deathYear = p => p && p.death ? year(p.death.date) : null;
  function isDeceased(p) {
    if (!p) return false;
    if (p.death && (p.death.date || p.death.place)) return true;
    const b = birthYear(p);
    return b !== null && (new Date().getFullYear() - b) > 105;
  }
  function lifespan(p) {
    const b = birthYear(p), d = deathYear(p);
    if (b === null && d === null) return '';
    const bs = b === null ? '?' : String(b);
    if (d !== null) return `${bs}–${d}`;
    if (isDeceased(p)) return `${bs}–?`;
    return `b. ${bs}`;
  }
  function age(p) {
    const b = p && p.birth ? parseDate(p.birth.date) : null;
    if (!b || b.year === null) return null;
    const end = p.death && p.death.date ? parseDate(p.death.date) : null;
    let ey, em, ed;
    if (end && end.year !== null) { ey = end.year; em = end.month || 7; ed = end.day || 1; }
    else if (isDeceased(p)) return null;
    else { const now = new Date(); ey = now.getFullYear(); em = now.getMonth() + 1; ed = now.getDate(); }
    let a = ey - b.year;
    if (em < (b.month || 7) || (em === (b.month || 7) && ed < (b.day || 1))) a--;
    return a;
  }
  function photo(p) {
    if (!p) return null;
    if (p.photo) return p.photo;
    const m = (p.media || []).find(x => x.type === 'photo' && x.file && x.portrait);
    return m ? m.file : null;
  }
  function confidence(p) {
    const c = p && p.link && p.link.confidence;
    return raw.confidenceLevels[c] ? c : 'unverified';
  }
  function confidenceLabel(key) { return (raw.confidenceLevels[key] || {}).label || key; }
  function confidenceDescription(key) { return (raw.confidenceLevels[key] || {}).description || ''; }
  const tags = p => (p && p.tags) || [];

  const parentsFamily = id => familyAsChild[id] || null;
  const parents = id => { const f = familyAsChild[id]; return f ? [f.husband, f.wife].map(get).filter(Boolean) : []; };
  const father = id => { const f = familyAsChild[id]; return f ? get(f.husband) : null; };
  const mother = id => { const f = familyAsChild[id]; return f ? get(f.wife) : null; };
  const spouseFamilies = id => (familiesAsSpouse[id] || []).slice().sort((a, b) => sortKey(a.marriage && a.marriage.date) - sortKey(b.marriage && b.marriage.date));
  const spouses = id => spouseFamilies(id).map(f => get(f.husband === id ? f.wife : f.husband)).filter(Boolean);
  const sortByBirth = list => list.slice().sort((a, b) => sortKey(a.birth && a.birth.date) - sortKey(b.birth && b.birth.date));
  function children(id) {
    const out = [];
    spouseFamilies(id).forEach(f => f.children.forEach(c => { const p = get(c); if (p) out.push(p); }));
    return sortByBirth(out);
  }
  function siblings(id) {
    const f = familyAsChild[id];
    return f ? sortByBirth(f.children.filter(c => c !== id).map(get).filter(Boolean)) : [];
  }
  function ancestorMap(id) {
    const map = {}, queue = [[id, 0]];
    while (queue.length) {
      const [pid, d] = queue.shift();
      parents(pid).forEach(p => { if (map[p.id] === undefined || map[p.id] > d + 1) { map[p.id] = d + 1; queue.push([p.id, d + 1]); } });
    }
    return map;
  }
  function descendantMap(id) {
    const map = {}, queue = [[id, 0]];
    while (queue.length) {
      const [pid, d] = queue.shift();
      children(pid).forEach(c => { if (map[c.id] === undefined) { map[c.id] = d + 1; queue.push([c.id, d + 1]); } });
    }
    return map;
  }

  /* ---------- Relationship calculator ---------- */
  const ordinal = n => { const s = ['th', 'st', 'nd', 'rd'], v = n % 100; return n + (s[(v - 20) % 10] || s[v] || s[0]); };
  const greats = n => n <= 0 ? '' : n === 1 ? 'great-' : n === 2 ? 'great-great-' : ordinal(n) + ' great-';
  const gendered = (p, m, f, u) => p.sex === 'M' ? m : p.sex === 'F' ? f : u;
  function describe(up, down, b) {
    if (down === 0) return up === 1 ? gendered(b, 'father', 'mother', 'parent') : greats(up - 2) + 'grand' + gendered(b, 'father', 'mother', 'parent');
    if (up === 0) return down === 1 ? gendered(b, 'son', 'daughter', 'child') : greats(down - 2) + 'grand' + gendered(b, 'son', 'daughter', 'child');
    if (up === 1 && down === 1) return gendered(b, 'brother', 'sister', 'sibling');
    if (down === 1) return greats(up - 2) + gendered(b, 'uncle', 'aunt', 'aunt/uncle');
    if (up === 1) return greats(down - 2) + gendered(b, 'nephew', 'niece', 'nibling');
    const degree = Math.min(up, down) - 1, removed = Math.abs(up - down);
    let s = ordinal(degree) + ' cousin';
    if (removed) s += ' ' + (removed === 1 ? 'once' : removed === 2 ? 'twice' : removed + ' times') + ' removed';
    return s;
  }
  function closest(aId, bId) {
    const ancA = ancestorMap(aId); ancA[aId] = 0;
    const ancB = ancestorMap(bId); ancB[bId] = 0;
    let best = null;
    Object.keys(ancA).forEach(k => {
      if (ancB[k] !== undefined) { const total = ancA[k] + ancB[k]; if (!best || total < best.total) best = { id: k, up: ancA[k], down: ancB[k], total }; }
    });
    return best;
  }
  function relationshipBlood(aId, bId) {
    if (aId === bId) return 'self';
    const best = closest(aId, bId);
    return best ? describe(best.up, best.down, get(bId)) : null;
  }
  /* How `b` relates to `a`: "b is a's <result>". */
  function relationship(aId, bId) {
    if (aId === bId) return 'self';
    const a = get(aId), b = get(bId);
    if (!a || !b) return null;
    const sf = spouseFamilies(aId).find(f => f.husband === bId || f.wife === bId);
    if (sf) return sf.status === 'engaged' ? gendered(b, 'fiancé', 'fiancée', 'fiancé(e)') : sf.status === 'divorced' ? gendered(b, 'former husband', 'former wife', 'former spouse') : gendered(b, 'husband', 'wife', 'spouse');
    const blood = relationshipBlood(aId, bId);
    if (blood) return blood;
    for (const s of spouses(aId)) { const r = relationshipBlood(s.id, bId); if (r && r !== 'self') return r + '-in-law'; }
    for (const s of spouses(bId)) { const r = relationshipBlood(aId, s.id); if (r && r !== 'self') { const f = spouseFamilies(bId).find(x => x.husband === s.id || x.wife === s.id); const former = f && f.status === 'divorced' ? 'former ' : ''; return former + gendered(b, 'husband', 'wife', 'spouse') + ' of ' + gendered(a, 'his', 'her', 'their') + ' ' + r; } }
    return null;
  }
  function relationshipSentence(aId, bId) {
    const a = get(aId), b = get(bId);
    if (!a || !b) return '';
    if (aId === bId) return `${fullName(b)} is you.`;
    const r = relationship(aId, bId);
    if (!r) return `No known relationship to ${shortName(a)} yet.`;
    const m = r.match(/^((?:former )?(?:husband|wife|spouse)) of (?:his|her|their) (.+)$/);
    if (m) return `${shortName(b)} is the ${m[1]} of ${shortName(a)}'s ${m[2]}.`;
    return `${shortName(b)} is the ${r} of ${shortName(a)}.`;
  }
  function relationshipShort(aId, bId) {
    if (aId === bId) return 'You';
    const r = relationship(aId, bId);
    if (!r) return '';
    return r.charAt(0).toUpperCase() + r.slice(1);
  }

  /* ---------- Search / aggregates ---------- */
  function search(q) {
    q = (q || '').trim().toLowerCase();
    if (!q) return [];
    const terms = q.split(/\s+/);
    return raw.people.filter(p => {
      const hay = [fullName(p), p.nickname, (p.aka || []).join(' '), p.birth && p.birth.place, p.death && p.death.place, birthYear(p), p.occupation, (p.tags || []).join(' '), confidence(p)].join(' ').toLowerCase();
      return terms.every(t => hay.includes(t));
    }).sort((a, b) => fullName(a).localeCompare(fullName(b)));
  }
  function events() {
    const ev = [];
    raw.people.forEach(p => {
      if (p.birth && p.birth.date) ev.push({ type: 'birth', date: p.birth.date, place: p.birth.place, people: [p] });
      if (p.death && p.death.date) ev.push({ type: 'death', date: p.death.date, place: p.death.place, people: [p] });
      if (p.burial && p.burial.date) ev.push({ type: 'event', title: 'Buried', date: p.burial.date, place: p.burial.place, people: [p] });
      (p.events || []).forEach(e => { if (e.date) ev.push({ type: 'event', title: e.title || 'Event', date: e.date, place: e.place, description: e.description, people: [p] }); });
      (p.residences || []).forEach(r => { if (r.date) ev.push({ type: 'residence', title: 'Lived in ' + (r.place || '?'), date: r.date.split(/[–-]/)[0], place: r.place, people: [p] }); });
      (p.military || []).forEach(m => { if (m.service) ev.push({ type: 'military', title: 'Military service' + (m.branch ? ', ' + m.branch : ''), date: m.service.split(/[–-]/)[0], description: [m.rank, m.unit, m.theatre].filter(Boolean).join(' · '), people: [p] }); });
    });
    raw.families.forEach(f => {
      if (f.marriage && f.marriage.date) ev.push({ type: 'marriage', date: f.marriage.date, place: f.marriage.place, people: [get(f.husband), get(f.wife)].filter(Boolean) });
      if (f.divorce && f.divorce.date) ev.push({ type: 'event', title: 'Divorced', date: f.divorce.date, place: f.divorce.place, people: [get(f.husband), get(f.wife)].filter(Boolean) });
    });
    raw.stories.forEach(s => { if (s.date) ev.push({ type: 'story', date: s.date, title: s.title, story: s, people: (s.people || []).map(get).filter(Boolean) }); });
    ev.forEach(e => { e.key = sortKey(e.date); });
    return ev.filter(e => e.key !== Infinity).sort((a, b) => a.key - b.key);
  }
  function surnames() {
    const counts = {};
    raw.people.forEach(p => { const s = p.surname || '(unknown)'; counts[s] = (counts[s] || 0) + 1; });
    return Object.keys(counts).map(k => ({ name: k, count: counts[k] })).sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
  }
  function allTags() {
    const counts = {};
    raw.people.forEach(p => (p.tags || []).forEach(t => { counts[t] = (counts[t] || 0) + 1; }));
    return Object.keys(counts).sort().map(k => ({ name: k, count: counts[k] }));
  }
  function allMedia() {
    const out = [];
    raw.people.forEach(p => (p.media || []).forEach(m => out.push(Object.assign({ owner: p }, m))));
    return out.sort((a, b) => sortKey(a.date) - sortKey(b.date));
  }
  const rootPerson = () => get(raw.rootPerson) || raw.people[0] || null;
  const owner = () => get(raw.owner) || rootPerson();
  const storiesFor = id => raw.stories.filter(s => (s.people || []).includes(id));
  const mediaFor = id => allMedia().filter(m => m.owner.id === id || (m.people || []).includes(id));

  window.Family = {
    raw, config: raw, title: raw.title || 'Family Tree', shortTitle: raw.shortTitle || raw.title || 'Family Tree', tagline: raw.tagline || '',
    get, all, families: raw.families, stories: raw.stories,
    fullName, shortName, firstName, initials, birthYear, deathYear, lifespan, age, isDeceased, photo,
    confidence, confidenceLabel, confidenceDescription, confidenceLevels: raw.confidenceLevels, tags, allTags,
    parseDate, formatDate, year, sortKey,
    parents, father, mother, parentsFamily, spouses, spouseFamilies, children, siblings, sortByBirth,
    ancestorMap, descendantMap, relationship, relationshipSentence, relationshipShort,
    search, events, surnames, allMedia, mediaFor, rootPerson, owner, storiesFor,
    familyById: id => familiesById[id] || null
  };
})();
