#!/usr/bin/env python3
"""Merge data/site.json + data/tree.json + data/research/*.json + data/stories.json
into data/family.js, the single file the website loads.

Usage:  python3 scripts/build.py            (run from the repository root)
        python3 scripts/build.py --check    (validate only, write nothing)

Research files overlay the tree: every key in data/research/<id>.json is
copied onto the person with that id (the "id" key itself is ignored).
"""
import argparse
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIDENCE = ("confirmed", "probable", "possible", "unverified")


def load(path, default):
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except FileNotFoundError:
        return default


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    os.chdir(ROOT)

    site = load("data/site.json", {})
    tree = load("data/tree.json", {"people": [], "families": []})
    stories = load("data/stories.json", [])
    problems, warnings = [], []

    people = {p["id"]: p for p in tree.get("people", [])}
    families = tree.get("families", [])
    for f in families:
        for key in ("husband", "wife"):
            if f.get(key) and f[key] not in people:
                problems.append("family %s: %s %s is not a person" % (f["id"], key, f[key]))
        for c in f.get("children", []):
            if c not in people:
                problems.append("family %s: child %s is not a person" % (f["id"], c))

    research_count = 0
    for path in sorted(glob.glob("data/research/*.json")):
        pid = os.path.splitext(os.path.basename(path))[0]
        try:
            r = load(path, {})
        except json.JSONDecodeError as e:
            problems.append("%s: invalid JSON (%s)" % (path, e))
            continue
        if pid not in people:
            warnings.append("%s: no person with id %s in tree.json (skipped)" % (path, pid))
            continue
        link = r.get("link") or {}
        if link.get("confidence") and link["confidence"] not in CONFIDENCE:
            problems.append("%s: confidence must be one of %s" % (path, ", ".join(CONFIDENCE)))
        for m in r.get("media", []):
            f = m.get("file")
            if f and not m.get("url") and not os.path.exists(f):
                warnings.append("%s: media file not found: %s" % (path, f))
        if r.get("photo") and not os.path.exists(r["photo"]):
            warnings.append("%s: photo not found: %s" % (path, r["photo"]))
        for k, v in r.items():
            if k != "id":
                people[pid][k] = v
        research_count += 1
    for p in people.values():
        tags = list(p.get("treeTags", [])) + list(p.get("tags", []))
        if tags:
            p["tags"] = sorted(set(tags))

    for s in stories:
        for pid in s.get("people", []):
            if pid not in people:
                warnings.append("story %s: unknown person %s" % (s.get("id"), pid))

    if site.get("rootPerson") and site["rootPerson"] not in people and people:
        warnings.append("site.json rootPerson %s not found; first person will be used" % site["rootPerson"])

    for w in warnings:
        print("warning: " + w, file=sys.stderr)
    for p in problems:
        print("error: " + p, file=sys.stderr)
    if problems:
        sys.exit(1)

    data = dict(site)
    data["sample"] = bool(tree.get("sample"))
    data["people"] = list(people.values())
    data["families"] = families
    data["stories"] = stories
    data["generated"] = __import__("datetime").date.today().isoformat()

    if args.check:
        print("ok: %d people, %d families, %d research files, %d stories" % (len(people), len(families), research_count, len(stories)))
        return
    with open("data/family.js", "w", encoding="utf-8") as fh:
        fh.write("/* GENERATED by scripts/build.py — do not edit. Edit data/tree.json, data/research/*.json, data/stories.json, data/site.json instead. */\n")
        fh.write("window.FAMILY_DATA = ")
        json.dump(data, fh, ensure_ascii=False, indent=1)
        fh.write(";\n")
    print("Wrote data/family.js: %d people, %d families, %d research files, %d stories" % (len(people), len(families), research_count, len(stories)))


if __name__ == "__main__":
    main()
